---
# Resources:
# University of Idaho templates
# https://github.com/thecdil/bootstrap-template
title: "SUSTAIN Southwest"
description: >
  A collaboration between University Hospitals Plymouth NHS Trust
  and University of Plymouth.
year: 2023
author: SUSTAIN Southwest team
search: true
defaults:
  - scope:
      path: "pages"
    values:
      layout: page
      permalink: /:basename:output_ext
# ignore stuff
exclude: [docs/, Rakefile, README.md, LICENSE]
